services:
  imap2rss:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      tags:
        - "imap2rss:dev"
    container_name: imap2rss
    restart: always
    env_file: ../.env
    ports:
      - 3043:3043
    volumes:
      - data:/data

volumes:
  data: null

networks: {}