services:
  imap2rss:
    image: aigoncharov/imap2rss:latest
    container_name: imap2rss
    restart: always
    environment:
      - TG_API_ID=REPLACE_ME
      - TG_API_HASH=REPLACE_ME
      - TG_PASSWORD=REPLACE_ME
      - BASE_URL=REPLACE_ME
    ports:
      - 3043:3043
    volumes:
      - data:/data

volumes:
  data: null

networks: {}